//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.Artiesten = new HashSet<Artiest>();
            this.Notities = new HashSet<Notitie>();
            this.ToDos = new HashSet<ToDo>();
        }
    
        public int EventID { get; set; }
        public string Eventnaam { get; set; }
        public int EventtypeID { get; set; }
        public System.DateTime Datum { get; set; }
        public string Startuur { get; set; }
        public string Einduur { get; set; }
        public Nullable<int> LocatieID { get; set; }
        public Nullable<int> KlantID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Artiest> Artiesten { get; set; }
        public virtual Klant Klant { get; set; }
        public virtual Locatie Locatie { get; set; }
        public virtual Eventtype Eventtype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notitie> Notities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToDo> ToDos { get; set; }
    }
}
