//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EventEntities : DbContext
    {
        public EventEntities()
            : base("name=EventEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artiest> Artiest { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Eventtype> Eventtype { get; set; }
        public virtual DbSet<Klant> Klant { get; set; }
        public virtual DbSet<Locatie> Locatie { get; set; }
        public virtual DbSet<Notitie> Notitie { get; set; }
        public virtual DbSet<ToDo> ToDo { get; set; }
    }
}
